title: Utkarsh Goyal
description: Pentration Tester
site_title: "@InsAneDark - Utkarsh Goyal"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: InsAneDark
blog_url: https://www.InsAneDark.github.io
email: Utkarsh@gmail.com
keybase_username: InsAneDark
twitter_username: InsAneDark
reddit_username: InsAneDark

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:

